services:
  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: cleanuparr
    ports:
      - 11011:11011
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - ./cleanuparr_config:/config
    networks:
      - media_network
    restart: unless-stopped
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - TUNNEL_TOKEN=[REDACTED]
    command: tunnel --no-autoupdate run
    networks:
      - media_network
networks:
  media_network:
    external: true
